# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.4.0
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Preparing the repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Go to the main directory
        run: cd $GITHUB_WORKSPACE

      # Runs a set of commands using the runners shell
      - name: Installing dependencies
        run: npm install

      - name: Building the application
        run: npm run publish
        env:
          GITHUB_SECRET_TOKEN: ${{ github.token }}
